SET NAMES utf8mb4;
START TRANSACTION;

ALTER TABLE customer_balance_movements
MODIFY COLUMN type ENUM(
  'PAYMENT_OVERAGE',
  'REFUND_STORE_CREDIT',
  'APPLIED_TO_ORDER',
  'MANUAL_ADJUSTMENT'
) NOT NULL;

COMMIT;