CREATE TABLE shipment_cost_shares (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  shipment_id BIGINT UNSIGNED NOT NULL,
  customer_package_id BIGINT UNSIGNED NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  assigned_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  share_method VARCHAR(30) NOT NULL,
  notes VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by_user_id BIGINT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_shipment_cost_shares_package (shipment_id, customer_package_id),
  KEY idx_shipment_cost_shares_shipment (shipment_id),
  KEY idx_shipment_cost_shares_package (customer_package_id),
  KEY idx_shipment_cost_shares_customer (customer_id),
  KEY idx_shipment_cost_shares_method (share_method),
  CONSTRAINT fk_shipment_cost_shares_shipment FOREIGN KEY (shipment_id) REFERENCES shipments(id),
  CONSTRAINT fk_shipment_cost_shares_package FOREIGN KEY (customer_package_id) REFERENCES customer_packages(id),
  CONSTRAINT fk_shipment_cost_shares_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_shipment_cost_shares_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_shipment_cost_shares_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);