CREATE TABLE shipment_payments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    shipment_id BIGINT UNSIGNED NOT NULL,
    cost_share_id BIGINT UNSIGNED NOT NULL,
    package_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    paid_by_customer_id BIGINT UNSIGNED NULL,
    amount DECIMAL(12,2) NOT NULL,
    payment_method VARCHAR(80) NULL,
    reference VARCHAR(120) NULL,
    notes VARCHAR(255) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'REGISTERED',
    registered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    registered_by BIGINT UNSIGNED NOT NULL,
    cancelled_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancel_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_shipment_payments_shipment (shipment_id),
    KEY idx_shipment_payments_cost_share (cost_share_id),
    KEY idx_shipment_payments_package (package_id),
    KEY idx_shipment_payments_customer (customer_id),
    KEY idx_shipment_payments_paid_by_customer (paid_by_customer_id),
    KEY idx_shipment_payments_status (status),
    CONSTRAINT fk_shipment_payments_shipment FOREIGN KEY (shipment_id) REFERENCES shipments(id),
    CONSTRAINT fk_shipment_payments_cost_share FOREIGN KEY (cost_share_id) REFERENCES shipment_cost_shares(id),
    CONSTRAINT fk_shipment_payments_package FOREIGN KEY (package_id) REFERENCES customer_packages(id),
    CONSTRAINT fk_shipment_payments_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_shipment_payments_paid_by_customer FOREIGN KEY (paid_by_customer_id) REFERENCES customers(id),
    CONSTRAINT fk_shipment_payments_registered_by FOREIGN KEY (registered_by) REFERENCES users(id),
    CONSTRAINT fk_shipment_payments_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id)
);
