export const designTokens = {
  colors: {
    primary: '#0f172a',
    secondary: '#475569',
    accent: '#2563eb',
    success: '#16a34a',
    successSoft: '#dcfce7',
    warning: '#d97706',
    warningSoft: '#fef3c7',
    danger: '#dc2626',
    dangerSoft: '#fee2e2',
    info: '#0ea5e9',
    infoSoft: '#e0f2fe',
    surface: '#ffffff',
    surfaceAlt: '#f8fafc',
    surfaceElevated: '#ffffff',
    surfaceMuted: '#f1f5f9',
    background: '#f8fafc',
    backgroundElevated: '#eef2f7',
    border: '#e2e8f0',
    borderSubtle: '#edf2f7',
    borderStrong: '#cbd5e1',
    textPrimary: '#0f172a',
    textSecondary: '#475569',
    textMuted: '#64748b',
    textOnPrimary: '#ffffff',
    textOnAccent: '#ffffff',
    muted: '#94a3b8',
    inputBackground: '#ffffff',
    inputBorder: '#cbd5e1',
    inputText: '#0f172a',
    inputPlaceholder: '#64748b',
    disabledBackground: '#e2e8f0',
    disabledText: '#64748b',
    focusRing: '#2563eb',
    accentSoft: '#dbeafe',
    overlay: 'rgba(15,23,42,0.38)',
    shadow: '#0f172a',
    shadowSoft: 'rgba(15,23,42,0.08)',
    alertSurface: '#fffbeb',
    alertBorder: '#f59e0b',
  },
  darkColors: {
    primary: '#e2e8f0',
    secondary: '#94a3b8',
    accent: '#93c5fd',
    success: '#86efac',
    successSoft: '#052e16',
    warning: '#fbbf24',
    warningSoft: '#3b2506',
    danger: '#fca5a5',
    dangerSoft: '#3f1218',
    info: '#93c5fd',
    infoSoft: '#0b2245',
    background: '#020617',
    backgroundElevated: '#07111f',
    surface: '#0f172a',
    surfaceAlt: '#111827',
    surfaceElevated: '#111827',
    surfaceMuted: '#1e293b',
    border: '#334155',
    borderSubtle: '#1e293b',
    borderStrong: '#475569',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted: '#94a3b8',
    textOnPrimary: '#020617',
    textOnAccent: '#020617',
    inputBackground: '#111827',
    inputBorder: '#64748b',
    inputText: '#f8fafc',
    inputPlaceholder: '#cbd5e1',
    disabledBackground: '#1e293b',
    disabledText: '#94a3b8',
    focusRing: '#93c5fd',
    accentSoft: '#172554',
    overlay: 'rgba(0,0,0,0.62)',
    shadow: '#000000',
    shadowSoft: 'rgba(0,0,0,0.28)',
    alertSurface: '#1f2937',
    alertBorder: '#fbbf24',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    '2xl': 32,
  },
  radius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    full: 999,
  },
  shadows: {
    card: {
      elevation: 1,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 3,
    },
    floating: {
      elevation: 4,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.14,
      shadowRadius: 10,
    },
    modal: {
      elevation: 8,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
    },
  },
  typography: {
    title: 24,
    subtitle: 17,
    body: 14,
    caption: 12,
    metric: 26,
  },
  layout: {
    sidebarWidth: 248,
    drawerWidthMobile: 280,
    drawerWidthTablet: 320,
    contentMaxWidth: 1240,
    cardGap: 14,
    pagePaddingDesktop: 24,
    pagePaddingTablet: 18,
    pagePaddingMobile: 14,
  },
  breakpoints: {
    mobile: 0,
    tablet: 768,
    desktop: 1024,
    desktopWide: 1200,
  },
} as const;

export type ViewVariant = 'admin' | 'operator' | 'seller' | 'supervisor' | 'noAccess' | 'default';

export const viewVariants: Record<
  ViewVariant,
  {
    tone: 'neutral' | 'success' | 'warning' | 'danger' | 'info';
    density: 'compact' | 'comfortable' | 'touch';
    emphasis: 'admin' | 'operational' | 'monitoring' | 'support' | 'blocked' | 'default';
  }
> = {
  admin: { tone: 'info', density: 'compact', emphasis: 'admin' },
  operator: { tone: 'success', density: 'touch', emphasis: 'operational' },
  seller: { tone: 'info', density: 'touch', emphasis: 'support' },
  supervisor: { tone: 'warning', density: 'comfortable', emphasis: 'monitoring' },
  noAccess: { tone: 'danger', density: 'comfortable', emphasis: 'blocked' },
  default: { tone: 'neutral', density: 'comfortable', emphasis: 'default' },
};
